### ISSUE TITLE
Empty 'Content-Encoding' header for images on S3

### ISSUE THREAD

**Issue by jonbuda** [fog/fog#3450] opened 2015-02-20 20:45 UTC
I'm using the Carrierwave gem with Rails, to help handle file uploading. It uses Fog in the background to upload to S3. On a recent update, up to 1.28.0, I've noticed that images have a 'Content-Encoding' header that is blank. The only reason I noticed is because iTunes was rejecting an image I uploaded for use in a Podcast. 

I pegged fog at version 1.22.1 in order to fix the problem. All subsequent versions seem to have the same problem, but I couldn't track down any changes that would cause it.

Here's what I see when I grab the headers for an image:

```
HTTP/1.1 200 OK
x-amz-id-2: LYcLaOf4sw1H2Tp13iNQun5F6yHj4pR7hpkBPQ+epsVBJ9+B9kWC/gmC9fTSYXli
x-amz-request-id: 7ABB8D8C248AF544
Date: Fri, 20 Feb 2015 20:39:02 GMT
Content-Encoding:
Last-Modified: Fri, 20 Feb 2015 20:38:43 GMT
ETag: "020d0b6dd02b728faebf0eb0496251ff"
Accept-Ranges: bytes
Content-Type: image/jpeg
Content-Length: 17208
Server: AmazonS3
```

**Comment by geemus** [comment] 2015-02-24 15:07
@fcheung could this maybe be related to the transition to v4 signatures? Thats the only thing that comes to mind, but maybe the timing is wrong.

**Comment by fcheung** [comment] 2015-02-24 15:09
Timing is wrong - v4 sigs were 1.25

**Comment by geemus** [comment] 2015-02-24 15:11
@fcheung Cool, thanks. I thought it might be, but suspected you might know more quickly/definitively. I guess it depends on what version he was on prior to going to 1.28.0 maybe?

@jonbuda Was the original update from 1.22.1 to 1.28.0? Or did you arrive at 1.22.1 as a working version in some other way?

**Comment by jonbuda** [comment] 2015-02-24 15:40
@geemus I didn't go directly from 1.22.1 to 1.28.0. I actually had some code in production for awhile before I used it. I noticed it first at 1.26.0, but it was present below that as well. Didn't seem to go away until 1.22.1

**Comment by jonbuda** [comment] 2015-02-24 23:03
@fcheung still could be? it's happening post-1.22.1

**Comment by fcheung** [comment] 2015-02-25 16:15
If it happens in versions 1.23 or 1.24 then it's almost certainly not sig v4.

If it happens in current versions, but not if you set signature_version => 2, then it probably is sig v4

There is some code in the v4 signature that manipulates the content encoding - for streaming uploads you have to implement this thing that's a bit liked chunked encoding in http, which means that content encoding gets set to `aws-chunked` or if you provide a content encoding `aws-chunked, "whatever you provided`

I suppose it's possible that at the other end it deletes the aws-chunked bit when it decodes it so it's left with the empty string. If that's the case then we should use `aws-chunked, identity` when we havent't been given an explicit encoding

**Comment by geemus** [comment] 2015-02-25 22:14
@fcheung ah, good point.

@jonbuda could you try with version 2 signature setting? That could help us narrow in on whether this is really a culprit or just a red herring. Thanks!

**Comment by lautis** [comment] 2015-03-20 23:22
I can confirm @fcheung's suspicions. This seems to be caused by the `aws-chunked` encoding.

Setting signature version to 2 makes the empty header go away. Similarly if the `Content-Enconding: aws-chunked` value is not set at all, the response didn't have a Content-Encoding header. This seemed to work on all files that I tested, although they were relatively small (<25MB).

**Comment by fcheung** [comment] 2015-03-21 14:44
Does https://github.com/fog/fog-aws/pull/75 help?

**Comment by fcheung** [comment] 2015-04-02 10:04
@jonbuda Any change you can try the linked fix & report back?

**Comment by jonbuda** [comment] 2015-04-02 15:46
@fcheung Seems to be working, as long as 'identity' is an OK Content-Encoding header. I think it's still set to v4, but I'm not sure where to set it to v2.

```
HTTP/1.1 200 OK
x-amz-id-2: wiA0yUoRnETcpYYW9xS/QtwMhGj9wPjxHkC3X8pQUaJlvdQfVs3WBsYE/T+HbaNr
x-amz-request-id: 820BB60B54C483BE
Date: Thu, 02 Apr 2015 15:33:21 GMT
Content-Encoding:  identity
Last-Modified: Thu, 02 Apr 2015 15:33:04 GMT
ETag: "68b3f7d5ffc31bee787abe426e44a131"
Accept-Ranges: bytes
Content-Type: image/jpeg
Content-Length: 21044
Server: AmazonS3
```

**Comment by fcheung** [comment] 2015-04-02 15:55
Cool, thanks for reporting back.

**Comment by geemus** [comment] 2015-04-02 18:49
Seems like this is likely fixed then, closing.

**Closed by geemus** 2015-04-02 18:49 UTC

**Comment by jaredrhine** [comment] 2015-04-10 15:14
For people searching on this issue, we have/had similar behavior. Using the asset_sync gem in Rails, we end up with S3 files that have two content-encoding headers on S3, one blank and one with the correct application/gzip. When served up over HTTP, some browsers pick the "gzip" and parse the CSS/JS correctly, other browsers pick the empty header and then get binary data while parsing.

We'll be testing whether 1.29.0 fixes our observed behavior along with the single-header case as well, and will open an issue if indeed that's a separate case. Just wanted to mention that in terms of test cases, there was breakage in 1.28 of 'empty content-encoding headers' whether an original content-encoding is set or not.
