### ISSUE TITLE
Ec2: If DescribeInstances fails (e.g. because of permissions) on server create, fog hangs

### ISSUE THREAD

**Issue by eherot** [fog/fog#2910] opened 2014-05-07 22:14 UTC
server.create just hangs until a timeout occurs.  In debug mode you can see excon retrying and receiving 403's repeatedly.

**Comment by plribeiro3000** [comment] 2015-02-02 13:12
@geemus This is related to aws, right?

Just to make sure before move this to the [`fog-aws`](https://github.com/fog/fog-aws) repo.

**Comment by eherot** [comment] 2015-02-02 18:12
My original request regarded aws. Not sure if the problem is unique to aws, though.

**Comment by geemus** [comment] 2015-02-02 21:25
It is an interesting question. I guess the problem is that wait_for can loop indefinitely, but 400 series errors are unlikely to resolve themselves. Perhaps it should be a change in the wait_for logic in fog-core actually?

**Comment by plribeiro3000** [comment] 2015-02-02 21:46
Hmmm. If it is related to the `wait_for` then we should move it to `fog-core` indeed. Can i move it? :smile:

**Comment by geemus** [comment] 2015-02-02 21:48
go for it, thanks!

**Comment by plribeiro3000** [comment] 2015-02-02 21:52
Closing in favor of fog/fog-core#129.

Thanks!

**Closed by plribeiro3000** 2015-02-02 21:52 UTC
