### ISSUE TITLE
Memory leak in Rackspace Cloud Files directory and file calls?

### ISSUE THREAD

**Issue by philayres** [fog/fog#3442] opened 2015-02-18 00:18 UTC
I'm using Fog to access Rackspace Cloud Files within EventMachine. I seem to be getting a memory leak related to the `Rackspace::Service#request` method. At this point I have not managed to separate out the code to make a simple example of the issue, but I'd like to see if the description of my current investigation can trigger any ideas around the real source of the problem. I've tried various Fog versions and have currently landed at 1.27.0 for testing.

I create a Fog connection up front and to get a single directory by name within an HTTP request handled by EventMachine (em-http-server)

    service = Fog::Storage.new(req_opt)
    # within an EventMachine deferred request
      service.directories.get(@full_container_name)
    # end the EventMachine request

I have separated out the Fog stuff, and have just returned data through my server and there is no leak. As soon as I hit service.directories.get the memory usage grows and grows. 

Now if I just do:

    (0..50).each do |d|
      service.directories.get(@full_container_name)
    end

The memory does not grow more than for a single call. So I believe that something is being held onto inside the first call within an EventMachine request.

If I do `service.directories.all` the memory does appear to leak too in a similar way, so its not just the `#get` method at fault.

For testing, I reduced the call to just do 

   service.directories.do_nothing

within the EM deferred request, where I created a dummy method in the Rackspace::Directories class. The memory does not grow in the same way.

Inside the Rackspace::Real class I created a similar dummy method and call this instead of `Rackspace::Real#get_container`, just to make sure. The memory jumps around a little more but does not grow endlessly.

This suggest to me that there is something happening inside the actual request that is not letting go. So I have just returned from `Rackspace::Service#request` immediately before `@connection.request`. Logging the `@connection` variable shows this connection is always the same (as expected). The memory does not grow if I don't call the `@connection.request` method.

When the `@connection.request` is reintroduced the memory grows indefinitely.

I'm assuming at this point I am close to hitting Excon code. But before I start wasting time over there too, I want to see if any of this discussion means anything to anybody here. I'm open to offers!

**Comment by philayres** [comment] 2015-02-18 13:46
To demonstrate the issue, see the Gist here: https://gist.github.com/philayres/2af8f67edbaf4470744a

Using EM.defer to provide a non-blocking server, the memory jump on each call to http://localhost:9999 is obvious. When just working in blocking mode (easily demonstrated by doing `work.call` and `callback.call` rather than `EM.defer`) the memory is pretty stable.

Does this help trigger any ideas where to look next?

**Comment by fcheung** [comment] 2015-02-19 10:31
I'm not familiar with rackspace, but perhaps you could try using the raw requests (https://github.com/fog/fog/tree/master/lib/fog/rackspace/requests/storage). If that doesn't leak then the problem is likely to be in the model layer.

**Comment by geemus** [comment] 2015-02-19 17:26
@mdarby - could you take a look? Thanks!

**Comment by mdarby** [comment] 2015-02-19 19:27
I will take a look.

**Comment by philayres** [comment] 2015-02-19 23:40
@mdarby - just let me know if I can do anything to help

**Comment by gabecase** [comment] 2015-04-22 17:56
@philayres @mdarby I'm a ruby developer at rackspace do you guys still need someone to take a look at this?

**Comment by mdarby** [comment] 2015-04-22 18:04
I'm sorry -- this fell off my radar. @gabecase Nice to meet you! I'm a Ruby dev at RAX as well.
If you want to take a crack at it, please do. Unfortunately I'm booked solid for the next couple weeks.

**Comment by kert-io** [comment] 2015-11-17 16:28
Any developments on this issue?  Still seeing the leak with Rackspace.

**Comment by plribeiro3000** [comment] 2016-03-10 20:07
Closing in favor of fog/fog-rackspace#4

**Closed by plribeiro3000** 2016-03-10 20:07 UTC
