### ISSUE TITLE
Fog::Service::NotFound openstack has no storage service

### ISSUE THREAD

**Issue by leemour** [fog/fog#4014] opened 2018-10-10 15:55 UTC
I'm using `fog-openstack` and it fails to load a fog service. The problem is in https://github.com/fog/fog-core/blob/master/lib/fog/core/services_mixin.rb#L44 where `require_service_provider_library` method is given `'storage'` as service but will only work if `'storage/storage'` is provided. 
I get this error when starting Rails:
```
[fog][DEPRECATION] Unable to require fog/openstack/storage
[fog][DEPRECATION] The format fog/storage/openstack is deprecated
Exiting
/home/leemour/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fog-core-2.1.2/lib/fog/core/services_mixin.rb:18:in `rescue in new': openstack has no storage service (Fog::Service::NotFound)
	from /home/leemour/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fog-core-2.1.2/lib/fog/core/services_mixin.rb:8:in `new'
	from /home/leemour/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/carrierwave-1.2.3/lib/carrierwave/uploader/configuration.rb:126:in `eager_load_fog'
	from /home/leemour/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/carrierwave-1.2.3/lib/carrierwave/uploader/configuration.rb:139:in `fog_credentials='
	from /home/leemour/Ruby/burobiz/config/initializers/carrierwave.rb:8:in `block in <main>'
	from /home/leemour/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/carrierwave-1.2.3/lib/carrierwave/uploader/configuration.rb:161:in `configure'
	from /home/leemour/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/carrierwave-1.2.3/lib/carrierwave.rb:14:in `configure'
	from /home/leemour/Ruby/burobiz/config/initializers/carrierwave.rb:1:in `<main>'
```
I'm using fog through `carrierwave` and have the following configuration:
```
CarrierWave.configure do |config|
  if Rails.env.test? || Rails.env.cucumber?
    config.storage = :file
    config.enable_processing = false
  else
    config.asset_host   = Rails.application.secrets.asset_host
    config.fog_provider = 'fog/openstack'
    config.fog_credentials = {
      provider:           'OpenStack',
      openstack_auth_url: 'https://api.selcdn.ru/v3',
      openstack_username: Rails.application.secrets.selectel[:username],
      openstack_api_key:  Rails.application.secrets.selectel[:password],
    }
    config.fog_directory  = Rails.application.secrets.selectel_container
    config.fog_public     = true
    config.fog_attributes = {
      cache_control: "public, max-age=#{365.days.to_i}"
    }
  end
end
```
I wonder if it's a problem with Carrierwave or with Fog or with Fog-OpenStack? Doesn't seem like `storage/storage` should be an appropriate service name. After overriding `Fog::ServicesMixin#require_service_provider_library` (to do nothing) it works as expected. I'm surprised not find an existing issue, maybe I'm doing smth wrong?

**Comment by geemus** [comment] 2018-10-11 15:13
Strange. It may relate to some recent cleanup/consistency fixing we've been trying to do. @plribeiro3000 do you think this could relate to the `storage::provider` to `provider::storage` transition?

**Comment by plribeiro3000** [comment] 2018-10-11 20:34
Not that im aware. Which version of `fog-openstack` are you using?

**Comment by leemour** [comment] 2018-10-12 08:37
@plribeiro3000 latest fog-openstack (1.0.3), fog-core (2.1.2).

**Comment by geemus** [comment] 2018-10-16 20:17
Weird. I'm not too surprised by the deprecation notice, which is probably something we should work to fix in carrierwave, but we had intended for those changes to be backwards compatible.

**Comment by hugogameiro** [comment] 2018-11-03 18:32
The exact same problem happens with PaperClip and the override of `Fog::ServicesMixin#require_service_provider_library` (to do nothing) fixes it for me too.

**Comment by plribeiro3000** [comment] 2018-11-03 21:17
Ok. Sorry for the huge delay here.

Looking through the code i believe the issue is related at how `fog-openstack` is structured.

Since the service is defined as `storage` using DSL and the constant name is `Fog::Openstack::Storage` it should have been defined in the file_path `lib/fog/openstack/storage` and not in `lib/fog/openstack/storage/storage`.

As of now do we have this problem in another provider or just `openstack`?

**Comment by plribeiro3000** [comment] 2018-11-03 21:19
If it is just `openstack` i rather send a PR fixing this (as i tried to do before without finishing it) rather then add more scenarios to this already bloated code that i wish we can kill at some point.

Can we confirm where does this happen?

**Comment by hugogameiro** [comment] 2018-11-03 21:32
AWS and Local on v2.1.2 are working on my testing environment, just `openstack` fails.

**Comment by plribeiro3000** [comment] 2018-11-03 21:59
As i thought. `fog-openstack` needs some cleanup. I will try to find some spare time to send a PR.

**Comment by geemus** [comment] 2018-11-06 18:06
@plribeiro3000 thanks for getting back to this. Just fixing it here sounds good when you have a chance. Thanks!

**Comment by plribeiro3000** [comment] 2018-11-06 18:12
@geemus I believe is more like something to be fixed on the provider itself.

If we do fix this here the problem will still remain because the issue is not necessarily here but rather the fact that autoloading classes and files is hard. And IMHO thats why we have bundler.

So i believe the best shot would be to fix this one time problem at `fog-openstack` now and try to converge this code here and leave this responsibility to `bundler`. 

My fear is that like all one time workarounds we did it was never a one time thing and most still exist in the codebase making it harder to maintain each day it pass by.

So maybe this time we could push it to `fog-openstack` and other providers to have a clear class and path definition. WDYT?

**Comment by geemus** [comment] 2018-11-06 18:14
Yeah, autoloading is definitely hard and brittle...

Fixing it for fog-openstack now sounds fine and working toward a better general solution later. I think that is what you are suggesting anyway?

**Comment by plribeiro3000** [comment] 2018-11-06 18:16
Yeap. =)

**Comment by plribeiro3000** [comment] 2018-11-06 18:16
Give me a day or two to work on `fog-openstack`. =)

**Comment by geemus** [comment] 2018-11-06 18:19
@plribeiro3000 sounds good, and thanks again for all your ongoing support!

**Comment by VincentSim** [comment] 2018-11-23 16:58
Hi all,
@plribeiro3000 did you managed to handle this bug ?

**Comment by plribeiro3000** [comment] 2018-11-25 14:31
@VincentSim Sorry, i did not. 

Would you be able to give it a try? It is as easy as move the files around.

**Comment by felipebatista** [comment] 2018-12-26 23:12
@VincentSim @plribeiro3000 I have submitted a Pull Request (https://github.com/fog/fog-openstack/pull/468) :smile: let's do some thumbs up :+1:

**Comment by felipebatista** [comment] 2019-01-23 10:58
version `1.0.8` released with this fix

https://github.com/fog/fog-openstack/releases/tag/v1.0.8

**Comment by plribeiro3000** [comment] 2019-01-23 13:21
Thanks everyone. Specially Felipe to work on the bugfix.  :+1:

Em qua, 23 de jan de 2019 08:58, Felipe Batista <notifications@github.com
escreveu:

**Comment by geemus** [comment] 2019-01-24 17:19
Yes, thanks!

**Closed** 2019-04-01 17:40 UTC
Labels: wontfix
