### ISSUE TITLE
require "fog" consuming 100% CPU for > 1 minute

### ISSUE THREAD

**Issue by philayres** [fog/fog#3430] opened 2015-02-05 04:22 UTC
I'm using fog to access Rackspace Cloud Files within an eventmachine environment.

At the top of my code, before any eventmachine reactor is invoked, I'm doing

    require 'fog'

Simple it would seem. On my powerful desktop PC this takes several seconds (much slower than other gems). On my low end cloud server (single vCPU, 1GB ram) it takes a minute or more to simply `require 'fog'` and during this time it consumes 95% or more of the server CPU.

I feel like this is something that has happened in the last few weeks. Other gems in the same environment load in under a second and the service starts up (minus this gem) in just a few seconds.

What is fog doing at this point in time? This is painfully poor performance. Coupled with some other memory leaks in this environment that I can only seem to link to fog, I feel like there has been a  regression, but I can't say when.

Any thoughts on where to look for this 'require' issue ?

**Comment by geemus** [comment] 2015-02-05 19:53
We are in the process of splitting fog out into a number of more granular gems, which we

**Comment by philayres** [comment] 2015-02-06 01:13
Is there is a fog-rackspace yet? I only need rackspace Cloud Files for this project.

**Comment by geemus** [comment] 2015-02-06 01:53
I think there is work-in-progress on that, but it hasn't landed quite yet. @mdarby can maybe speake more to the specifics.

**Comment by mdarby** [comment] 2015-02-06 14:49
Unfortunately the last I heard was that the "gem registry" was being developed? That was several weeks ago.

**Comment by mdarby** [comment] 2015-02-06 15:05
Just tried requiring the gem on my machine:
![about this mac 2015-02-06 10-04-55](https://cloud.githubusercontent.com/assets/2805/6081468/b0e0c780-ade7-11e4-918e-87347ae8b572.jpg)


`ruby script.rb  43.01s user 1.96s system 98% cpu 45.599 total`

**Comment by tokengeek** [comment] 2015-02-06 21:23
I ran a little script against this and there was a **big** performance regression with `fog-v1.26.0`

https://gist.github.com/tokengeek/19dd1d96c923a3d19d90

Went from 2s to 10s

I ran `git bisect` to find where the performance regression occurred and it was 7d047e7

```
legion:~/code/fog ruby 2.1.5 on master 
⚡ git co 319fed9       
Note: checking out '319fed9'.
HEAD is now at 319fed9... [aws|compute] reload security group by id when available
legion:~/code/fog ruby 2.1.5 on  
⚡ time ruby -Ilib -e 'require "fog"'
ruby -Ilib -e 'require "fog"'  2.20s user 0.15s system 99% cpu 2.346 total
legion:~/code/fog ruby 2.1.5 on  
⚡ git co 7d047e7
Previous HEAD position was 319fed9... [aws|compute] reload security group by id when available
HEAD is now at 7d047e7... Moved Ecloud to a modular gem
legion:~/code/fog ruby 2.1.5 on  
⚡ time ruby -Ilib -e 'require "fog"'
ruby -Ilib -e 'require "fog"'  10.14s user 0.54s system 99% cpu 10.690 total
legion:~/code/fog ruby 2.1.5 on  
```

Unfortunately the obvious trick or removing the references to "ecloud" is not fixing the performance issue.

Reverting that commit (bringing the provider back in) is also NOT helping so there doesn't appear to be some magic caused by it's presence.

If I remove all the new dependent gems, performance drops down to ~2s again.

So:
1) definitely a regression
2) not sure why the `fog-ecloud` commit was _the_ commit that triggered a big jump
3) it's not degrading linearly (still ~11s on master) after a number of other gems extracted

Due to the way some providers have implemented things, provider registry is looking more like a fog 2.0 thing since it won't be backwards compatible.

**Comment by geemus** [comment] 2015-02-11 16:58
I don't know why that was the straw that broke the camels back, but I do have some ideas for possible improvements that may help. I suspect this may come down to the search path for "/lib/fog" being enormous now and possibly some load order stuff. Some things that might be worth exploring:

1. I think it would be good to add simple `lib/fog-#{service}.rb` to each gem, so that they can be required as `fog-#{service}` without traversing potentially a ton of `/lib/fog` stuff. (ditto fog-core/xml/json). This file would simply be a proxy (it would just require, via relative path referring to itself to avoid the search tree, `/lib/fog/#{service}`. We would then change the requires within these (and within fog/fog) to use these instead.
2. Within the gems, it might also be worth moving more of the requires that appear within `/lib/fog/#{service}.rb` to being relative to that file (instead of going through the entire "/lib/fog" search space, which now includes tons of stuff.

It is hard to benchmark/know for sure, but they seem like reasonable/good things to do anyway. Thoughts? I suspect these would be positive changes regardless.

**Comment by plribeiro3000** [comment] 2015-02-13 18:27
I agree with you @geemus. I will update the providers i have access and submit PR's to the ones i don't asap.

**Comment by geemus** [comment] 2015-02-14 16:49
@plribeiro3000 thanks, just let me know if I can help out in any way (and or which ones you don't have access to and I can tackle those, or give you access).

**Comment by philayres** [comment] 2015-02-20 00:17
@tokengeek - thanks for identifying which release caused this. I just had a chance to roll back my underpowered cloud server to 1.24 and it now starts up in a handful of seconds. I had to forcibly `gem uninstall` a bunch of fog gems to get this to work though, otherwise just bundling the older version didn't make any difference. (I feel like it has a lower memory footprint too, but that's probably not true)

Just in case anybody else needs this, here's the command line I used

    gem uninstall fog  fog-atmos fog-aws fog-brightbox fog-core fog-ecloud fog-json fog-profitbricks fog-radosgw fog-sakuracloud fog-serverlove fog-softlayer fog-storm_on_demand fog-terremark fog-vmfusion fog-voxel fog-xml -aIx

    bundle update

**Comment by plribeiro3000** [comment] 2015-03-30 04:41
@philayres Could you try my branch and see if it fix the issue?

`gem 'fog', github: 'fog', branch: 'fix-loading-time'`

**Comment by philayres** [comment] 2015-04-03 01:49
@plribeiro3000 I have only been able to test your branch on my development machine, not my cloud server (since I need to wait for memory leaks that appeared after 1.24 have disappeared too, and that takes some testing). But my initial impression is that this is better than it was. Good work!

**Comment by plribeiro3000** [comment] 2015-04-03 02:00
@philayres Awesome to know. If my patches aren't the better solution at least we know it is in the right path. Can you tell how much did the branch improved the loading?

**Comment by philayres** [comment] 2015-04-03 14:21
@plribeiro3000 I just got a chance to try this on my original "problem" server. Your branch seems to have resolved the startup problem. I'm down to about 3-4 seconds for the load, which appears to be comparable to the v1.24 version. I'd say this patch is a good direction.

**Comment by plribeiro3000** [comment] 2015-04-04 23:11
@philayres We are almost there. Missing only the biggest providers which we have to move carefully and with assistance of the maintainers.

Gotta let you know once we finish it. =)

**Comment by mdarby** [comment] 2015-04-04 23:56
@plribeiro3000 I'd love to pitch in on behalf of Rackspace and/or OpenStack.

**Comment by plribeiro3000** [comment] 2015-04-06 12:37
Hey @mdarby ! I believe we don't we need to mix in any of the providers that are in `fog` since for already handle it. The main issue was with the extracted providers but we are missing only `fog-softlayer`, `fog-profitbricks`, `fog-local`, `fog-brightbox` and `fog-json`.

There are open PR's for all of them already. Most of the work left is to review all of them, merge and release a patch version. You are welcome to chime in and help review them.

**Comment by geemus** [comment] 2015-04-07 19:41
Thanks!

**Comment by plribeiro3000** [comment] 2015-06-28 20:18
There is just providers left to close this issue which are `fog-brightbox` and `fog-profitbricks`.
After a while i've managed to work both PR's again and make a solution that the maintainers might feel more comfortable to merge. Once it happens we are good to close this regression issue and start preparing `2.0.0` release.

**Comment by plribeiro3000** [comment] 2015-07-24 20:22
@philayres We finally got all fog gems fixed for this regression.

The problem was that fog has a self builded solution to reduce the amount of classes and files loaded but as we started migrating them outside we lost that feature.

The short solution was to use `autoload` and relative paths. @geemus is already working towards a long term solution but for the time being thats the one we are going to support.

Thank you for your time and patient!

**Closed by plribeiro3000** 2015-07-24 20:22 UTC
