### ISSUE TITLE
Work towards service based gems

### ISSUE THREAD

**Issue by tokengeek** [fog/fog#2718] opened 2014-02-27 09:47 UTC
This is an old idea I've probably mentioned it before but worth highlighting for discussion.

Since fog was originally an abstraction layer, we should investigate ways to create service based gems instead of provider centric ones.

This benefits tools that do one thing such as vagrant plugins (compute) or carrierwave uploading (storage) by requiring an abstraction layer over multiple providers who offer that one service.

The interface code should be part of `fog-core` but a `fog-compute` gem bundles providers who offer compute services.

This does introduce old dependency problems since AWS does everything any service gem pulls in XML stuff which becomes an annoying glitch if you want to use a standard interface over another DNS provider.

We could look at smarter loading of gems. I had a buggy as hell prototype that looked for `fog-*` gems installed on the system containing a registration class, tested some stuff (if their own dependencies were met) and required them.

The registration code allowed you to query a service for providers that were available and you had credentials for. I stopped because testing with Shindo syntax was too slow.

Anyway before we run off and create 40 provider based gems that **enforce** lock in due to incompatible interfaces we should probably go back to the original benefit of `fog` as abstracting half a dozen cloud services.

/cc @geemus but all are invited to comment.

**Comment by geemus** [comment] 2018-07-30 17:11
Close as duplicate of #3942

**Closed by geemus** 2018-07-30 17:11 UTC
Labels: core, discussion, summit, wontfix
