### ISSUE TITLE
duplicate key :openstack_region

### ISSUE THREAD

**Issue by nulian** [fog/fog#3407] opened 2015-01-19 11:02 UTC
With ruby 2.2 I get the following warning

fog-1.27.0/lib/fog/openstack/volume.rb:191: warning: duplicated key at line 196 ignored: :openstack_region

Which is correct openstack region is assigned twice.

**Comment by plribeiro3000** [comment] 2015-01-19 11:17
Hey @nulian . Thank you for opening an issue.

This is a duplicate of #3401 which was already solved.

**Closed by plribeiro3000** 2015-01-19 11:17 UTC
